# Generated by Django 3.1 on 2022-03-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mscrmbusinesstypeselect',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='mscrmintrest',
            options={'ordering': ['id']},
        ),
    ]
