# Generated by Django 3.1 on 2022-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0024_auto_20220329_1024'),
        ('msCrm', '0002_auto_20220330_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscrmuser',
            name='intrests',
            field=models.ManyToManyField(blank=True, to='catalogAlbum.CatalogAlbum', verbose_name='intrested'),
        ),
    ]
