# Generated by Django 3.1 on 2022-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0027_remove_catalogalbum_order'),
        ('msCrm', '0003_auto_20220331_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsCrmIntrestsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('intrests', models.ManyToManyField(blank=True, to='catalogAlbum.CatalogAlbum', verbose_name='intrested')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
