# Generated by Django 3.1 on 2022-06-29 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0027_remove_catalogalbum_order'),
        ('msCrm', '0004_mscrmintrestsgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsCrmBusinessSelectToIntrests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessSelect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='msCrm.mscrmbusinesstypeselect', verbose_name='business')),
                ('intrests', models.ManyToManyField(blank=True, to='catalogAlbum.CatalogAlbum', verbose_name='intrested')),
            ],
        ),
    ]
