# Generated by Django 3.1 on 2022-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0005_mscrmbusinessselecttointrests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mscrmbusinesstypeselect',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='mscrmbusinesstypeselect',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
