# Generated by Django 3.1 on 2022-07-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0005_auto_20220709_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mscrmwhatsappmessagessent',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='mscrmwhatsappmessagessent',
            name='crmUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsappMessagesSent', to='msCrm.mscrmuser', verbose_name='crmUser'),
        ),
    ]
