# Generated by Django 3.1 on 2022-07-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0006_auto_20220704_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=100, verbose_name='business name')),
                ('businessTypeCustom', models.CharField(blank=True, max_length=100, null=True, verbose_name='business type custom')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('businessTypeSelects', models.ManyToManyField(to='msCrm.MsCrmBusinessTypeSelect', verbose_name='business type')),
            ],
        ),
    ]
