# Generated by Django 3.1 on 2022-07-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0006_auto_20220709_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscrmwhasappimageproduct',
            name='whatsapp_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsappImageProducts', to='msCrm.mscrmwhatsappmessage', verbose_name='whatsappMessage'),
        ),
    ]
