# Generated by Django 3.1 on 2022-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0007_leadsubmit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsubmit',
            name='businessTypeCustom',
        ),
        migrations.RemoveField(
            model_name='leadsubmit',
            name='businessTypeSelects',
        ),
        migrations.AddField(
            model_name='leadsubmit',
            name='businessType',
            field=models.CharField(default=' ', max_length=254, verbose_name='business type'),
            preserve_default=False,
        ),
    ]
