# Generated by Django 3.1 on 2022-07-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0007_auto_20220709_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscrmwhatsappmessagessent',
            name='whatsapp_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsappMessagesSent', to='msCrm.mscrmwhatsappmessage', verbose_name='whatsappMessage'),
        ),
    ]
