# Generated by Django 3.1 on 2022-07-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_clienttype_tariff'),
        ('msCrm', '0008_auto_20220704_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscrmuser',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='ms_crm_users', to='client.Client', verbose_name='clients'),
        ),
    ]
