# Generated by Django 3.1 on 2022-08-22 07:45

from django.db import migrations

def fix_crm_dups(apps, schema_editor):
    MsCrmUser = apps.get_model('msCrm', 'MsCrmUser')
    users = MsCrmUser.objects.all().distinct('phone')
    for user in users:
        if(user.phone != None):
            if MsCrmUser.objects.filter(phone=user.phone).count() > 1:
                # delete all the duplicates except the last updated_at without  Negative indexing 
                dups = MsCrmUser.objects.filter(phone=user.phone).order_by('-updated_at')[1:]
                for dup in dups:
                    print('deleting', dup.id)
                    dup.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0008_auto_20220704_1206'),
    ]

    operations = [
        migrations.RunPython(fix_crm_dups),
    ]
