# Generated by Django 3.1 on 2022-08-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0009_mscrmuser_clients'),
        ('msCrm', '0008_auto_20220709_1116'),
    ]

    operations = [
    ]
