# Generated by Django 3.1 on 2022-08-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0010_auto_20220822_1046'),
        ('msCrm', '0010_merge_20220809_1125'),
    ]

    operations = [
    ]
