# Generated by Django 3.1 on 2022-11-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0011_merge_20220825_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMsCrmUserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
