# Generated by Django 3.1 on 2023-05-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0012_importmscrmusertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsCrmMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('businessSelect', models.ManyToManyField(to='msCrm.MsCrmBusinessTypeSelect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
