# Generated by Django 3.1 on 2024-04-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0014_auto_20230529_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportMsCrmUserTask',
        ),
        migrations.DeleteModel(
            name='LeadSubmit',
        ),
        migrations.RemoveField(
            model_name='mscrmbusinessselecttointrests',
            name='businessSelect',
        ),
        migrations.RemoveField(
            model_name='mscrmbusinessselecttointrests',
            name='intrests',
        ),
        migrations.DeleteModel(
            name='MsCrmIntrest',
        ),
        migrations.RemoveField(
            model_name='mscrmintrestsgroups',
            name='intrests',
        ),
        migrations.RemoveField(
            model_name='mscrmmessage',
            name='businessSelect',
        ),
        migrations.RemoveField(
            model_name='mscrmuser',
            name='businessSelect',
        ),
        migrations.RemoveField(
            model_name='mscrmuser',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='mscrmuser',
            name='intrests',
        ),
        migrations.RemoveField(
            model_name='mscrmwhasappimageproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mscrmwhasappimageproduct',
            name='whatsapp_message',
        ),
        migrations.RemoveField(
            model_name='mscrmwhatsappmessagessent',
            name='crmUser',
        ),
        migrations.RemoveField(
            model_name='mscrmwhatsappmessagessent',
            name='whatsapp_message',
        ),
        migrations.DeleteModel(
            name='MsCrmBusinessSelectToIntrests',
        ),
        migrations.DeleteModel(
            name='MsCrmBusinessTypeSelect',
        ),
        migrations.DeleteModel(
            name='MsCrmIntrestsGroups',
        ),
        migrations.DeleteModel(
            name='MsCrmMessage',
        ),
        migrations.DeleteModel(
            name='MsCrmUser',
        ),
        migrations.DeleteModel(
            name='MsCrmWhasappImageProduct',
        ),
        migrations.DeleteModel(
            name='MsCrmWhatsappMessage',
        ),
        migrations.DeleteModel(
            name='MsCrmWhatsappMessagesSent',
        ),
    ]
