# Generated by Django 3.0.8 on 2021-02-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
        ('catalogImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='colors',
            field=models.ManyToManyField(to='color.Color'),
        ),
    ]
