# Generated by Django 3.0.8 on 2021-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0001_initial'),
        ('catalogImages', '0002_catalogimage_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='sizes',
            field=models.ManyToManyField(to='productSize.ProductSize'),
        ),
    ]
