# Generated by Django 3.0.8 on 2021-03-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0004_auto_20210322_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='title',
            field=models.CharField(max_length=120, verbose_name='כותרת'),
        ),
    ]
