# Generated by Django 3.0.8 on 2021-03-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0005_auto_20210325_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='big_discount',
            field=models.BooleanField(default=False),
        ),
    ]
