# Generated by Django 3.0.8 on 2021-03-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0006_catalogimage_big_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='discount',
            field=models.CharField(choices=[('', 'ללא הנחה'), ('file_name1.gif', '10% הנחה'), ('file_name2.gif', '20% הנחה')], default='', max_length=50),
        ),
    ]
