# Generated by Django 3.0.8 on 2021-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0007_catalogimage_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='discount',
            field=models.CharField(choices=[('', 'ללא הנחה'), ('/static/assets/catalog/imgs/discount_10.png', '10% הנחה'), ('/static/assets/catalog/imgs/discount_20.png', '20% הנחה')], default='', max_length=50),
        ),
    ]
