# Generated by Django 3.0.8 on 2021-03-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0008_auto_20210325_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='renew_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='renew_for',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='timer',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
