# Generated by Django 3.0.8 on 2021-03-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0009_auto_20210329_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='renew_after',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
