# Generated by Django 3.0.8 on 2021-03-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0010_auto_20210329_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='renew_after',
        ),
        migrations.RemoveField(
            model_name='catalogimage',
            name='renew_for',
        ),
        migrations.RemoveField(
            model_name='catalogimage',
            name='timer',
        ),
    ]
