# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0011_auto_20210329_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogimage',
            options={'ordering': ['throughimage__image_order'], 'verbose_name': 'Catalog image', 'verbose_name_plural': 'Catalog images'},
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image thumbnail'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
    ]
