# Generated by Django 3.0.8 on 2021-04-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0012_auto_20210330_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogimage',
            options={'verbose_name': 'Catalog image', 'verbose_name_plural': 'Catalog images'},
        ),
    ]
