# Generated by Django 3.0.8 on 2021-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0013_auto_20210406_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='discount',
            field=models.CharField(blank=True, choices=[('', 'ללא הנחה'), ('/static/assets/catalog/imgs/discount_10.png', '10% הנחה'), ('/static/assets/catalog/imgs/discount_20.png', '20% הנחה')], default='', max_length=50, null=True),
        ),
    ]
