# Generated by Django 3.0.8 on 2021-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0015_auto_20210411_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='client_price',
            field=models.FloatField(default=1, verbose_name='client price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='cost_price',
            field=models.FloatField(default=1, verbose_name='cost price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='recomended_price',
            field=models.FloatField(default=1, verbose_name='recomended price'),
            preserve_default=False,
        ),
    ]
