# Generated by Django 3.0.8 on 2021-08-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0015_auto_20210411_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='big_discount',
        ),
    ]
