# Generated by Django 3.0.8 on 2021-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0016_remove_catalogimage_big_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='can_tag',
            field=models.BooleanField(default=False, verbose_name='can tag'),
        ),
    ]
