# Generated by Django 3.0.8 on 2021-09-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0016_auto_20210912_1452'),
        ('catalogImages', '0017_catalogimage_can_tag'),
    ]

    operations = [
    ]
