# Generated by Django 3.0.8 on 2021-09-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0002_auto_20210330_0407'),
        ('catalogImages', '0021_auto_20210913_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='packingType',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='packingType.PackingType'),
        ),
    ]
