# Generated by Django 3.0.8 on 2021-09-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20210330_0407'),
        ('color', '0002_auto_20210330_0407'),
        ('packingType', '0002_auto_20210330_0407'),
        ('productSize', '0002_auto_20210330_0407'),
        ('catalogImages', '0022_catalogimage_packingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode'),
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='whatsapp_text',
            field=models.TextField(blank=True, null=True, verbose_name='whatsapp text'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='colors',
            field=models.ManyToManyField(to='color.Color', verbose_name='colors'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='packingType',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='packingType.PackingType', verbose_name='packing type'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='providers',
            field=models.ManyToManyField(to='provider.Provider', verbose_name='providers'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='sizes',
            field=models.ManyToManyField(to='productSize.ProductSize', verbose_name='sizes'),
        ),
    ]
