# Generated by Django 3.0.8 on 2021-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0023_auto_20210913_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='client_price',
            field=models.FloatField(verbose_name='store price'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='recomended_price',
            field=models.FloatField(verbose_name='private client price'),
        ),
    ]
