# Generated by Django 3.0.8 on 2021-09-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0002_auto_20210330_0407'),
        ('catalogImages', '0024_auto_20210914_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='packingType',
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='packingTypeClient',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='PTclient', to='packingType.PackingType', verbose_name='packing type for client'),
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='packingTypeProvider',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='PTprovider', to='packingType.PackingType', verbose_name='packing type from provider'),
        ),
    ]
