# Generated by Django 3.0.8 on 2021-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0025_auto_20210919_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
