# Generated by Django 3.0.8 on 2021-09-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImageDetail', '0001_initial'),
        ('catalogImages', '0026_catalogimage_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='detailTabel',
            field=models.ManyToManyField(to='catalogImageDetail.CatalogImageDetail', verbose_name='mini-tabel'),
        ),
    ]
