# Generated by Django 3.0.8 on 2021-10-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0029_auto_20211004_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='client_price',
            field=models.FloatField(default=1, verbose_name='store price'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='cost_price',
            field=models.FloatField(default=1, verbose_name='cost price'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='recomended_price',
            field=models.FloatField(default=1, verbose_name='private client price'),
        ),
    ]
