# Generated by Django 3.0.8 on 2021-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0031_auto_20211013_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='free_text',
            field=models.TextField(blank=True, null=True, verbose_name='free text'),
        ),
    ]
