# Generated by Django 3.0.8 on 2021-10-30 00:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0032_catalogimage_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='cimage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='product_image'),
        ),
    ]
