# Generated by Django 3.1 on 2022-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0036_auto_20211031_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='image_thumbnail',
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
