# Generated by Django 3.1 on 2022-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0037_auto_20220106_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='local image'),
        ),
    ]
