# Generated by Django 3.1 on 2022-01-06 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0038_catalogimage_local_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
