# Generated by Django 3.1 on 2022-01-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0039_catalogimage_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogimage',
            old_name='local_image',
            new_name='image_thumbnail',
        ),
    ]
