# Generated by Django 3.1 on 2022-01-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0041_auto_20220116_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='show_sizes_popup',
            field=models.BooleanField(default=False, verbose_name='show sizes popup'),
        ),
    ]
