# Generated by Django 3.1 on 2022-01-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0042_catalogimage_show_sizes_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='update_image_to_cloudinary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='show_sizes_popup',
            field=models.BooleanField(default=True, verbose_name='show sizes popup'),
        ),
    ]
