# Generated by Django 3.1 on 2022-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0046_auto_20220131_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImageVarient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='varients',
            field=models.ManyToManyField(to='catalogImages.CatalogImageVarient', verbose_name='varients'),
        ),
    ]
