# Generated by Django 3.1 on 2022-03-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0047_auto_20220308_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimagevarient',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
