# Generated by Django 3.1 on 2022-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0048_auto_20220309_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='qyt',
            field=models.IntegerField(default=0, verbose_name='qyt'),
        ),
    ]
