# Generated by Django 3.1 on 2022-03-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0049_catalogimage_qyt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='varients',
            field=models.ManyToManyField(blank=True, to='catalogImages.CatalogImageVarient', verbose_name='varients'),
        ),
    ]
