# Generated by Django 3.1 on 2022-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0050_auto_20220327_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='out_of_stock',
            field=models.BooleanField(default=False, verbose_name='out of stock'),
        ),
    ]
