# Generated by Django 3.1 on 2022-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0051_catalogimage_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='has_physical_barcode',
            field=models.BooleanField(default=False, verbose_name='has physical barcode'),
        ),
    ]
