# Generated by Django 3.1 on 2022-04-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0052_catalogimage_has_physical_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Is Hidden'),
        ),
    ]
