# Generated by Django 3.1 on 2022-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0053_catalogimage_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
