# Generated by Django 3.1 on 2022-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0054_auto_20220414_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='client_price',
            field=models.FloatField(default=1, verbose_name='store price, before tax'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='cost_price',
            field=models.FloatField(default=1, verbose_name='cost price, before tax'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='recomended_price',
            field=models.FloatField(default=1, verbose_name='private client price, after tax'),
        ),
    ]
