# Generated by Django 3.1 on 2022-05-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0055_auto_20220424_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogimagevarient',
            options={'ordering': ('id',)},
        ),
    ]
