# Generated by Django 3.1 on 2022-07-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0056_auto_20220525_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogimage',
            options={'ordering': ('-date_created',), 'verbose_name': 'Catalog image', 'verbose_name_plural': 'Catalog images'},
        ),
    ]
