# Generated by Django 3.1 on 2022-08-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0057_auto_20220713_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
