# Generated by Django 3.1 on 2022-08-25 09:16

from django.db import migrations
from core.utils import fixUniqeSlug


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0059_catalogimage_main_public_album'),
    ]

    operations = [
        migrations.RunPython(fixUniqeSlug)
    ]
