# Generated by Django 3.1 on 2022-08-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0060_auto_20220825_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
