# Generated by Django 3.1 on 2022-09-02 08:04

from django.db import migrations


def set_main_public_album(apps=None, schema_editor=None):
    catalogImage = apps.get_model('catalogImages', 'CatalogImage')
    all_images = catalogImage.objects.all()
    for img in all_images:
        if img.main_public_album == None:
            albs = img.albums.filter(is_public=True)
            if albs.exists():
                img.main_public_album = albs.first()
                img.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0061_auto_20220830_1059'),
    ]

    operations = [
        migrations.RunPython(set_main_public_album)
    ]
