# Generated by Django 3.1 on 2023-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0002_auto_20210330_0407'),
        ('catalogImages', '0063_auto_20230612_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='colors',
            field=models.ManyToManyField(to='productColor.ProductColor', verbose_name='colors'),
        ),
    ]
