# Generated by Django 3.1 on 2024-04-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0064_auto_20230612_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='clientPrices',
        ),
        migrations.RemoveField(
            model_name='catalogimage',
            name='detailTabel',
        ),
    ]
