# Generated by Django 3.1 on 2024-04-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0065_auto_20240411_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogimagevarient',
            options={'ordering': ('id',), 'verbose_name': 'Product varient', 'verbose_name_plural': 'Product varients'},
        ),
    ]
