# Generated by Django 3.1 on 2024-04-18 11:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20220619_1353'),
        ('catalogImages', '0066_auto_20240411_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='catalogimage',
            name='image_thumbnail',
        ),
        migrations.RemoveField(
            model_name='catalogimage',
            name='update_image_to_cloudinary',
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='providers',
            field=models.ManyToManyField(blank=True, to='provider.Provider', verbose_name='providers'),
        ),
    ]
