# Generated by Django 3.1 on 2024-04-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0068_auto_20240418_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='can_tag',
        ),
        migrations.RemoveField(
            model_name='catalogimage',
            name='cimage',
        ),
        migrations.RemoveField(
            model_name='catalogimage',
            name='has_physical_barcode',
        ),
    ]
