# Generated by Django 3.1 on 2024-04-21 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0041_auto_20240421_0618'),
        ('catalogImages', '0069_auto_20240421_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='main_public_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_album', to='catalogAlbum.catalogalbum', verbose_name='main album'),
        ),
    ]
