# Generated by Django 3.1 on 2024-04-21 08:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0070_auto_20240421_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='תמונת מוצר')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('catalogImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogImages.catalogimage', verbose_name='catalog image')),
            ],
        ),
    ]
