# Generated by Django 3.0.8 on 2020-11-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productColor', '0001_initial'),
        ('packingType', '0001_initial'),
        ('provider', '0001_initial'),
        ('product', '0001_initial'),
        ('productSize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerMakat', models.CharField(blank=True, max_length=50, verbose_name='מק"ט של הספק')),
                ('amount', models.IntegerField(default=0, verbose_name='כמות אצלנו')),
                ('provider_has_stock', models.BooleanField(default=True, verbose_name='קיים אצל הספק')),
                ('provider_resupply_date', models.DateTimeField(blank=True, null=True, verbose_name='תאריך חידוש מלאי אצל הספק')),
                ('packingType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='packingType.PackingType', verbose_name='שיטת אריזה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.Product', verbose_name='שם מוצר')),
                ('productColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productColor.ProductColor', verbose_name='צבע')),
                ('productSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productSize.ProductSize', verbose_name='גודל')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='provider.Provider', verbose_name='ספק מוצר')),
            ],
            options={
                'verbose_name': 'מלאי',
                'verbose_name_plural': 'מלאים',
                'default_related_name': 'stocks',
            },
        ),
    ]
