# Generated by Django 3.0.8 on 2020-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buy_cost',
            field=models.FloatField(default=0, verbose_name='מחיר עלות'),
        ),
        migrations.AddField(
            model_name='stock',
            name='const_inst_client_max',
            field=models.FloatField(default=0, null=True, verbose_name='עד'),
        ),
        migrations.AddField(
            model_name='stock',
            name='const_inst_client_min',
            field=models.FloatField(default=0, null=True, verbose_name='מחיר לקוח מוסדי ללא מע"מ מ'),
        ),
        migrations.AddField(
            model_name='stock',
            name='const_sing_client',
            field=models.FloatField(default=0, verbose_name='מחיר לקוח בודד כולל מע"מ'),
        ),
    ]
