# Generated by Django 3.0.8 on 2020-11-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlofaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(verbose_name='מספר')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('supportedProducts', models.ManyToManyField(related_name='supportedProducts', to='product.Product', verbose_name='supported products')),
            ],
            options={
                'verbose_name': 'סוג גלופה',
                'verbose_name_plural': 'סוגי גלופה',
            },
        ),
    ]
