# Generated by Django 3.0.8 on 2020-12-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glofa_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlofaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='GlofaImages', verbose_name='תמונה')),
            ],
            options={
                'verbose_name': 'glofa image',
                'verbose_name_plural': 'glofa images',
            },
        ),
        migrations.CreateModel(
            name='GlofaImageTypeConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cords', models.CharField(max_length=150)),
                ('shape', models.CharField(choices=[('rect', 'rect'), ('circle', 'circle'), ('poly', 'poly')], default='rect', max_length=10)),
                ('glofaImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glofa_types.GlofaImage')),
                ('glofaType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glofa_types.GlofaType')),
            ],
        ),
        migrations.AddField(
            model_name='glofaimage',
            name='glofaLocation',
            field=models.ManyToManyField(through='glofa_types.GlofaImageTypeConnection', to='glofa_types.GlofaType'),
        ),
    ]
