# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glofa_types', '0002_auto_20201216_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glofatype',
            options={'verbose_name': 'glofa type', 'verbose_name_plural': 'glofa types'},
        ),
        migrations.AlterField(
            model_name='glofaimage',
            name='image',
            field=models.ImageField(upload_to='GlofaImages', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='glofatype',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='glofatype',
            name='num',
            field=models.PositiveIntegerField(verbose_name='number'),
        ),
    ]
