# Generated by Django 3.1 on 2024-04-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glofa_types', '0003_auto_20210330_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glofaimagetypeconnection',
            name='glofaImage',
        ),
        migrations.RemoveField(
            model_name='glofaimagetypeconnection',
            name='glofaType',
        ),
        migrations.RemoveField(
            model_name='glofatype',
            name='supportedProducts',
        ),
        migrations.DeleteModel(
            name='GlofaImage',
        ),
        migrations.DeleteModel(
            name='GlofaImageTypeConnection',
        ),
        migrations.DeleteModel(
            name='GlofaType',
        ),
    ]
