# Generated by Django 3.1 on 2022-02-18 12:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_auto_20210330_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#0000ffff', image_field=None, max_length=18, samples=None, verbose_name='color'),
        ),
    ]
