# Generated by Django 3.1 on 2022-02-22 08:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0004_auto_20220218_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF00', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FFFFFF00', 'transparent')], verbose_name='color'),
        ),
    ]
