# Generated by Django 3.1 on 2024-04-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productSize', '0011_auto_20230702_1246'),
        ('color', '0005_auto_20220222_1012'),
        ('catalogImages', '0064_auto_20230612_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.ForeignKey(blank=True, default=76, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='color.color')),
                ('size', models.ForeignKey(blank=True, default=108, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='productSize.productsize')),
                ('varient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogImages.catalogimagevarient')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', models.ManyToManyField(blank=True, related_name='orderItem', to='cart.CartItemEntry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogImages.catalogimage')),
            ],
            options={
                'ordering': ['product__title'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('privateCompany', models.CharField(blank=True, max_length=100, verbose_name='ח.פ')),
                ('message', models.TextField(blank=True)),
                ('is_inventory_check', models.BooleanField(default=False)),
                ('is_order', models.BooleanField(default=False)),
                ('is_price_proposal', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, related_name='mycart', to='cart.CartItem')),
            ],
        ),
    ]
