# Generated by Django 3.0.8 on 2020-12-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFlowClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם')),
                ('email', models.EmailField(max_length=254, verbose_name='שם')),
                ('phone', models.CharField(max_length=50, verbose_name='טלפון')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('message', models.CharField(max_length=200, verbose_name='message')),
            ],
        ),
    ]
