# Generated by Django 3.0.8 on 2020-12-22 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freeFlow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeflowclient',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeflowclient',
            name='privatePerson',
            field=models.BooleanField(default=True, verbose_name='is private person'),
        ),
    ]
