# Generated by Django 3.0.8 on 2020-12-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeFlow', '0002_auto_20201222_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeflowclient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='אימייל'),
        ),
    ]
