# Generated by Django 3.0.8 on 2020-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeFlow', '0003_auto_20201224_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFlowContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroH3', models.CharField(max_length=100)),
                ('heroH1', models.CharField(max_length=100)),
                ('heroH2', models.CharField(max_length=200)),
                ('heroBtn', models.CharField(max_length=50)),
                ('aboutTitle', models.CharField(max_length=150)),
            ],
        ),
    ]
