# Generated by Django 3.0.8 on 2021-01-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeFlow', '0006_freeflowcontent_nav_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeflowcontent',
            name='aboutItem1Description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeflowcontent',
            name='aboutItem1Title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeflowcontent',
            name='aboutP',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
