# Generated by Django 3.0.8 on 2021-01-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeFlow', '0007_auto_20210126_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeflowcontent',
            name='aboutItem2Description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeflowcontent',
            name='aboutItem2Title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeflowcontent',
            name='aboutItem3Description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeflowcontent',
            name='aboutItem3Title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
