# Generated by Django 3.0.8 on 2021-01-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeFlow', '0009_auto_20210127_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFlowStores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
    ]
