# Generated by Django 3.1 on 2021-12-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='price'),
        ),
    ]
