# Generated by Django 3.1 on 2021-12-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0002_pricetable_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountbrakepoint',
            name='number',
            field=models.FloatField(verbose_name='number'),
        ),
    ]
