# Generated by Django 3.1 on 2021-12-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0002_auto_20211222_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campainproduct',
            name='priceTable',
        ),
        migrations.AddField(
            model_name='campainproduct',
            name='priceTable',
            field=models.ManyToManyField(blank=True, null=True, to='campains.PriceTable', verbose_name='price table'),
        ),
    ]
