# Generated by Django 3.1 on 2021-12-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0003_auto_20211221_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
    ]
