# Generated by Django 3.1 on 2021-12-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0036_auto_20211031_1249'),
        ('campains', '0003_auto_20211222_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campainproduct',
            name='priceTable',
            field=models.ManyToManyField(blank=True, to='campains.PriceTable', verbose_name='price table'),
        ),
        migrations.AlterUniqueTogether(
            name='campainproduct',
            unique_together={('monthCampain', 'catalogImage')},
        ),
    ]
