# Generated by Django 3.1 on 2021-12-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0004_auto_20211222_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountbrakepoint',
            name='text',
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='paymentType',
            field=models.CharField(blank=True, choices=[('cash', 'מזומן'), ('credit', 'שוטף'), ('other', 'אחר')], max_length=10, null=True, verbose_name='payment type'),
        ),
    ]
