# Generated by Django 3.1 on 2021-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0004_auto_20211221_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campainproduct',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='campainproduct',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
