# Generated by Django 3.1 on 2021-12-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0005_auto_20211226_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetable',
            name='amountBrakepoint',
        ),
        migrations.AddField(
            model_name='pricetable',
            name='amount',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='paymentType',
            field=models.CharField(blank=True, choices=[('מזומן', 'מזומן'), ('שוטף', 'שוטף'), ('אחר', 'אחר')], max_length=10, null=True, verbose_name='payment type'),
        ),
    ]
