# Generated by Django 3.1 on 2021-12-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0006_auto_20211226_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetable',
            name='paymentType',
        ),
        migrations.RemoveField(
            model_name='pricetable',
            name='price',
        ),
        migrations.AddField(
            model_name='pricetable',
            name='cach_price',
            field=models.FloatField(default=0, verbose_name='cach price'),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='credit_price',
            field=models.FloatField(default=0, verbose_name='credit price'),
        ),
    ]
