# Generated by Django 3.1 on 2021-12-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0007_auto_20211226_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'price table', 'verbose_name_plural': 'price tables'},
        ),
        migrations.AlterUniqueTogether(
            name='pricetable',
            unique_together={('amount', 'cach_price', 'credit_price')},
        ),
    ]
