# Generated by Django 3.1 on 2021-12-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20211212_1507'),
        ('campains', '0008_auto_20211226_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthcampain',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='monthcampain',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='monthcampain',
            name='users',
            field=models.ManyToManyField(blank=True, to='client.Client', verbose_name='users'),
        ),
    ]
