# Generated by Django 3.1 on 2021-12-27 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0009_auto_20211227_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthcampain',
            name='endTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='monthcampain',
            name='startTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='start time'),
        ),
    ]
