# Generated by Django 3.1 on 2021-12-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0017_auto_20211214_1726'),
        ('campains', '0010_auto_20211227_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthcampain',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogAlbum.catalogalbum', verbose_name='album'),
        ),
    ]
