# Generated by Django 3.1 on 2022-01-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0011_monthcampain_album'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricetable',
            unique_together=set(),
        ),
    ]
