# Generated by Django 3.1 on 2022-06-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_clienttype_tariff'),
        ('core', '0037_auto_20220425_1409'),
        ('campains', '0017_cartcampains'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartCampains',
            new_name='CartCampain',
        ),
    ]
