# Generated by Django 3.1 on 2022-07-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0056_auto_20220525_1232'),
        ('campains', '0018_auto_20220604_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campainproduct',
            name='priceTable',
        ),
        migrations.AddField(
            model_name='campainproduct',
            name='newPrice',
            field=models.FloatField(default=0, verbose_name='new price'),
        ),
        migrations.AlterField(
            model_name='campainproduct',
            name='catalogImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogImages.catalogimage', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='campainproduct',
            name='monthCampain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campains.monthcampain', verbose_name='month campain'),
        ),
    ]
