# Generated by Django 3.1 on 2024-04-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0019_auto_20220712_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmountBrakepoint',
        ),
        migrations.AlterUniqueTogether(
            name='campainproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='campainproduct',
            name='catalogImage',
        ),
        migrations.RemoveField(
            model_name='campainproduct',
            name='monthCampain',
        ),
        migrations.RemoveField(
            model_name='cartcampain',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartcampain',
            name='users',
        ),
        migrations.RemoveField(
            model_name='monthcampain',
            name='album',
        ),
        migrations.RemoveField(
            model_name='monthcampain',
            name='products',
        ),
        migrations.RemoveField(
            model_name='monthcampain',
            name='users',
        ),
        migrations.DeleteModel(
            name='PaymantType',
        ),
        migrations.DeleteModel(
            name='PriceTable',
        ),
        migrations.DeleteModel(
            name='CampainProduct',
        ),
        migrations.DeleteModel(
            name='CartCampain',
        ),
        migrations.DeleteModel(
            name='MonthCampain',
        ),
    ]
