# Generated by Django 3.1 on 2022-03-09 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color', '0005_auto_20220222_1012'),
        ('catalogImages', '0048_auto_20220309_0825'),
        ('provider', '0003_auto_20211013_1947'),
        ('core', '0029_auto_20220303_0547'),
        ('client', '0017_auto_20220301_1057'),
        ('productSize', '0002_auto_20210330_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clientProvider', models.CharField(blank=True, max_length=255, null=True)),
                ('clientBuyPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ergent', models.BooleanField(default=False)),
                ('prining', models.BooleanField(default=False)),
                ('embroidery', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogImages.catalogimage')),
                ('provider', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='provider.provider')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.productsize')),
                ('varient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogImages.catalogimagevarient')),
            ],
        ),
        migrations.CreateModel(
            name='MOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'חדש'), ('in_progress', 'בתהליך'), ('done', 'גמור')], max_length=100)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sveltecartmodal')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('products', models.ManyToManyField(blank=True, to='morders.MOrderItem')),
            ],
        ),
    ]
