# Generated by Django 3.1 on 2022-03-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20211013_1947'),
        ('morders', '0002_morder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morderitem',
            name='provider',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.SET_DEFAULT, to='provider.provider'),
        ),
    ]
