# Generated by Django 3.1 on 2022-03-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0005_auto_20220222_1012'),
        ('productSize', '0002_auto_20210330_0407'),
        ('morders', '0003_auto_20220309_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morderitem',
            name='color',
            field=models.ForeignKey(default=76, on_delete=django.db.models.deletion.SET_DEFAULT, to='color.color'),
        ),
        migrations.AlterField(
            model_name='morderitem',
            name='size',
            field=models.ForeignKey(default=108, on_delete=django.db.models.deletion.SET_DEFAULT, to='productSize.productsize'),
        ),
    ]
