# Generated by Django 3.1 on 2022-03-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0005_auto_20220222_1012'),
        ('productSize', '0002_auto_20210330_0407'),
        ('morders', '0004_auto_20220322_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morderitem',
            name='color',
            field=models.ForeignKey(blank=True, default=76, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='color.color'),
        ),
        migrations.AlterField(
            model_name='morderitem',
            name='size',
            field=models.ForeignKey(blank=True, default=108, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='productSize.productsize'),
        ),
    ]
