# Generated by Django 3.1 on 2022-03-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20211013_1947'),
        ('morders', '0006_auto_20220324_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morderitem',
            name='provider',
        ),
        migrations.AddField(
            model_name='morderitem',
            name='providers',
            field=models.ManyToManyField(blank=True, to='provider.Provider'),
        ),
    ]
