# Generated by Django 3.1 on 2022-03-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0007_auto_20220327_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='order', to='morders.MOrderItem'),
        ),
    ]
