# Generated by Django 3.1 on 2022-04-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20220414_1236'),
        ('morders', '0009_auto_20220327_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='client.client'),
        ),
    ]
