# Generated by Django 3.1 on 2022-05-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0011_auto_20220417_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morderitem',
            options={'ordering': ['product__title']},
        ),
    ]
