# Generated by Django 3.1 on 2022-05-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0012_auto_20220518_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morder',
            options={'ordering': ['-created']},
        ),
    ]
