# Generated by Django 3.1 on 2022-06-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0012_auto_20220517_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='morder',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='morder',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
