# Generated by Django 3.1 on 2022-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0013_auto_20220622_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='status',
            field=models.CharField(choices=[('חדש', 'חדש'), ('סחורה הוזמנה', 'סחורה הוזמנה'), ('מוכן לליקוט', 'מוכן לליקוט'), ('ארוז מוכן למשלוח', 'ארוז מוכן למשלוח'), ('בהדפסה', 'בהדפסה'), ('סופק', 'סופק')], max_length=100),
        ),
    ]
