# Generated by Django 3.1 on 2022-05-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0002_auto_20210330_0407'),
        ('color', '0005_auto_20220222_1012'),
        ('catalogImages', '0056_auto_20220525_1232'),
        ('provider', '0003_auto_20211013_1947'),
        ('morders', '0013_auto_20220525_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('has_physical_barcode', models.BooleanField(default=False)),
                ('color', models.ForeignKey(blank=True, default=76, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='color.color')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
                ('size', models.ForeignKey(blank=True, default=108, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='productSize.productsize')),
                ('varient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogImages.catalogimagevarient')),
            ],
        ),
        migrations.AddField(
            model_name='morderitem',
            name='taken',
            field=models.ManyToManyField(blank=True, related_name='product', to='morders.TakenInventory'),
        ),
    ]
