# Generated by Django 3.1 on 2022-05-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0015_auto_20220529_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='freezeTakenInventory',
            field=models.BooleanField(default=False),
        ),
    ]
