# Generated by Django 3.1 on 2022-05-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0016_morder_freezetakeninventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
