# Generated by Django 3.1 on 2022-06-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0002_auto_20210330_0407'),
        ('color', '0005_auto_20220222_1012'),
        ('provider', '0003_auto_20211013_1947'),
        ('morders', '0021_auto_20220531_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeninventory',
            name='color',
            field=models.ForeignKey(default=76, on_delete=django.db.models.deletion.SET_DEFAULT, to='color.color'),
        ),
        migrations.AlterField(
            model_name='takeninventory',
            name='provider',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='takeninventory',
            name='size',
            field=models.ForeignKey(default=108, on_delete=django.db.models.deletion.SET_DEFAULT, to='productSize.productsize'),
        ),
    ]
