# Generated by Django 3.1 on 2022-06-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0022_auto_20220602_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morderitem',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='orderItem', to='morders.MOrderItemEntry'),
        ),
        migrations.AlterField(
            model_name='morderitem',
            name='taken',
            field=models.ManyToManyField(blank=True, related_name='orderItem', to='morders.TakenInventory'),
        ),
    ]
