# Generated by Django 3.1 on 2022-06-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0024_auto_20220606_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeninventory',
            name='barcode',
        ),
    ]
