# Generated by Django 3.1 on 2022-06-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0026_auto_20220609_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerrequest',
            options={'ordering': ['provider', 'color', 'varient', 'force_physical_barcode', 'size']},
        ),
    ]
