# Generated by Django 3.1 on 2022-06-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0012_auto_20220517_1059'),
        ('morders', '0027_auto_20220619_1322'),
    ]

    operations = [
    ]
