# Generated by Django 3.1 on 2022-06-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0029_auto_20220626_1605'),
        ('morders', '0028_merge_20220621_1223'),
    ]

    operations = [
    ]
