# Generated by Django 3.1 on 2022-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0030_merge_20220629_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='morder',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='morder',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
