# Generated by Django 3.1 on 2022-08-23 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0031_auto_20220705_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morderitem',
            options={'ordering': ['created_at', 'product__title']},
        ),
        migrations.AddField(
            model_name='morderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
