# Generated by Django 3.1 on 2022-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0033_auto_20220825_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='status_msg',
            field=models.TextField(blank=True, null=True, verbose_name='status message'),
        ),
        migrations.AlterField(
            model_name='morder',
            name='status',
            field=models.CharField(choices=[('new', 'חדש'), ('in_progress', 'סחורה הוזמנה'), ('in_progress2', 'מוכן לליקוט'), ('in_progress3', 'בהדפסה'), ('in_progress4', 'מוכן בבית דפוס'), ('in_progress5', 'ארוז מוכן למשלוח'), ('done', 'סופק')], default='new', max_length=100),
        ),
    ]
