# Generated by Django 3.1 on 2022-09-08 08:38

from django.db import migrations, models


def re_save_all_morder_to_calc_total_sell_price(apps, schema_editor):
    #MOrder = apps.get_model('morders', 'MOrder')
    from morders.models import MOrder
    all_objs = MOrder.objects.all()
    for obj in all_objs:
        #obj.total_sell_price = obj.prop_totalPrice
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0034_auto_20220904_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='total_sell_price',
            field=models.FloatField(
                default=0, verbose_name='total sell price'),
        ),
        migrations.AlterField(
            model_name='morder',
            name='status',
            field=models.CharField(choices=[('new', 'חדש'), ('price_proposal', 'הצעת מחיר'), ('in_progress', 'סחורה הוזמנה'), ('in_progress2', 'מוכן לליקוט'), (
                'in_progress3', 'בהדפסה'), ('in_progress4', 'מוכן בבית דפוס'), ('in_progress5', 'ארוז מוכן למשלוח'), ('done', 'סופק')], default='new', max_length=100),
        ),
        migrations.RunPython(re_save_all_morder_to_calc_total_sell_price),
    ]
