# Generated by Django 3.1 on 2022-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0035_auto_20220908_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='last_status_updated',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last status updated'),
        ),
    ]
