# Generated by Django 3.1 on 2023-01-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0036_morder_last_status_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('sort_order', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='morder',
            name='status2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='morders.morderstatus'),
        ),
    ]
