# Generated by Django 3.1 on 2023-01-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0038_auto_20230122_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='last_sheet_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last sheet update'),
        ),
        migrations.AddField(
            model_name='morder',
            name='spreed_sheet_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
