# Generated by Django 3.1 on 2023-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0039_auto_20230124_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morder',
            old_name='spreed_sheet_url',
            new_name='gid',
        ),
    ]
