# Generated by Django 3.1 on 2023-01-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0040_auto_20230124_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='morderitementry',
            name='sheets_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='morderitementry',
            name='sheets_taken_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
