# Generated by Django 3.1 on 2023-01-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0041_auto_20230126_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morderitementry',
            name='sheets_taken_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
