# Generated by Django 3.1 on 2023-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0042_auto_20230130_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='export_to_suppliers',
            field=models.BooleanField(default=False),
        ),
    ]
