# Generated by Django 3.1 on 2023-05-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0043_morder_export_to_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='price_proposal_sheetname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
