# Generated by Django 3.1 on 2023-05-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0044_morder_price_proposal_sheetname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morder',
            old_name='price_proposal_sheetname',
            new_name='price_proposal_sheetid',
        ),
    ]
