# Generated by Django 3.1 on 2023-06-14 07:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0045_auto_20230531_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='morderstatus',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF00', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FFFFFF00', 'transparent')], verbose_name='color'),
        ),
    ]
