# Generated by Django 3.1 on 2023-06-15 14:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0047_auto_20230614_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morderstatus',
            name='color',
            field=colorfield.fields.ColorField(default='#FF12E2FF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FFFFFF00', 'transparent')], verbose_name='color'),
        ),
    ]
