# Generated by Django 3.1 on 2023-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0048_auto_20230615_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='last_notify_order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morder',
            name='last_notify_order_total_price',
            field=models.FloatField(default=0, verbose_name='last notify order total price'),
        ),
    ]
