# Generated by Django 3.1 on 2023-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0049_auto_20230702_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='order_sheet_archived',
            field=models.BooleanField(default=False),
        ),
    ]
