# Generated by Django 3.1 on 2024-04-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0050_morder_order_sheet_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morderitem',
            name='taken',
        ),
        migrations.RemoveField(
            model_name='morderitem',
            name='toProviders',
        ),
    ]
