# Generated by Django 3.1 on 2023-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0052_auto_20230926_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='private_company',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
