# Generated by Django 3.1 on 2024-04-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbee', '0008_auto_20240411_0654'),
        ('docsSignature', '0015_auto_20240411_0654'),
        ('morders', '0052_remove_collectedinventory_warehousestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morder',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='morder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='morder',
            name='products',
        ),
        migrations.RemoveField(
            model_name='morder',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='morderitem',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='morderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='morderitem',
            name='providers',
        ),
        migrations.RemoveField(
            model_name='morderitementry',
            name='color',
        ),
        migrations.RemoveField(
            model_name='morderitementry',
            name='size',
        ),
        migrations.RemoveField(
            model_name='morderitementry',
            name='varient',
        ),
        migrations.RemoveField(
            model_name='takeninventory',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='takeninventory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='takeninventory',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='takeninventory',
            name='size',
        ),
        migrations.RemoveField(
            model_name='takeninventory',
            name='varient',
        ),
        migrations.DeleteModel(
            name='CollectedInventory',
        ),
        migrations.DeleteModel(
            name='MOrder',
        ),
        migrations.DeleteModel(
            name='MOrderItem',
        ),
        migrations.DeleteModel(
            name='MOrderItemEntry',
        ),
        migrations.DeleteModel(
            name='MorderStatus',
        ),
        migrations.DeleteModel(
            name='TakenInventory',
        ),
    ]
