# Generated by Django 3.1 on 2023-09-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0053_morder_private_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
