# Generated by Django 3.1 on 2023-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0054_morder_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='settlement',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
