# Generated by Django 3.0.8 on 2020-11-12 12:51

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogImages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='כותרת')),
                ('slug', models.SlugField(max_length=120, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThroughImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('catalogAlbum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogAlbum.CatalogAlbum')),
                ('catalogImage', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogImages.CatalogImage')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', through='catalogAlbum.ThroughImage', to='catalogImages.CatalogImage'),
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogAlbum.CatalogAlbum'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='catalogalbum',
        #     unique_together={('slug', 'parent')},
        # ),
    ]
