# Generated by Django 3.0.8 on 2021-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0002_catalogalbum_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='האם פומבי'),
        ),
        migrations.AlterField(
            model_name='catalogalbum',
            name='slug',
            field=models.SlugField(max_length=120, verbose_name='סלאג'),
        ),
    ]
