# Generated by Django 3.0.8 on 2021-02-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0001_initial'),
        ('catalogAlbum', '0004_auto_20210221_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', through='catalogAlbum.ThroughImage', to='catalogImages.CatalogImage'),
        ),
    ]
