# Generated by Django 3.0.8 on 2021-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0005_auto_20210221_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='throughimage',
            options={'ordering': ['image_order']},
        ),
        migrations.AddField(
            model_name='throughimage',
            name='image_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
