# Generated by Django 3.0.8 on 2021-03-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0003_catalogimage_sizes'),
        ('catalogAlbum', '0006_auto_20210224_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='album', through='catalogAlbum.ThroughImage', to='catalogImages.CatalogImage'),
        ),
    ]
