# Generated by Django 3.0.8 on 2021-03-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0007_auto_20210317_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='keywords',
            field=models.TextField(default='', verbose_name='keyworks'),
        ),
    ]
