# Generated by Django 3.0.8 on 2021-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0010_auto_20210323_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='fotter',
            field=models.TextField(blank=True, default='', verbose_name='fotter'),
        ),
    ]
