# Generated by Django 3.0.8 on 2021-03-29 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0011_catalogalbum_fotter'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='renew_after',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1), null=True),
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='renew_for',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=3), null=True),
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='timer',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
