# Generated by Django 3.0.8 on 2021-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0012_auto_20210329_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
