# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0013_auto_20210329_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='catalogalbum',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='catalogalbum',
            name='slug',
            field=models.SlugField(max_length=120, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='catalogalbum',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
    ]
