# Generated by Django 3.0.8 on 2021-09-13 09:38

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0023_auto_20210913_0835'),
        ('catalogAlbum', '0014_auto_20210330_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='album', through='catalogAlbum.ThroughImage', to='catalogImages.CatalogImage', verbose_name='album list'),
        ),
        migrations.AlterField(
            model_name='throughimage',
            name='catalogAlbum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogAlbum.CatalogAlbum', verbose_name='catalog album'),
        ),
        migrations.AlterField(
            model_name='throughimage',
            name='catalogImage',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogImages.CatalogImage', verbose_name='catalog image'),
        ),
    ]
