# Generated by Django 3.0.8 on 2021-09-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0023_auto_20210913_0835'),
        ('catalogAlbum', '0015_auto_20210913_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='albums', through='catalogAlbum.ThroughImage', to='catalogImages.CatalogImage', verbose_name='album list'),
        ),
    ]
