# Generated by Django 3.1 on 2021-12-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0017_auto_20211214_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='is_campain',
            field=models.BooleanField(default=False, verbose_name='is campain'),
        ),
    ]
