# Generated by Django 3.1 on 2022-01-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campains', '0015_remove_monthcampain_album'),
        ('catalogAlbum', '0018_catalogalbum_is_campain'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='campain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='campains.monthcampain'),
        ),
    ]
