# Generated by Django 3.1 on 2022-01-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0019_catalogalbum_campain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogalbum',
            name='campain',
        ),
    ]
