# Generated by Django 3.1 on 2022-01-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0020_remove_catalogalbum_campain'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='catalogAlbum/', verbose_name='image'),
        ),
    ]
