# Generated by Django 3.1 on 2022-01-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0021_catalogalbum_cimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='cimage',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='cimage'),
        ),
    ]
