# Generated by Django 3.1 on 2022-01-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0022_auto_20220112_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='cimage',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='cimage'),
        ),
    ]
