# Generated by Django 3.1 on 2022-03-29 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0023_auto_20220112_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopLevelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('my_order', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, unique=True)),
            ],
            options={
                'ordering': ('my_order',),
            },
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='topLevelCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topLevelCategory', to='catalogAlbum.toplevelcategory'),
        ),
    ]
