# Generated by Django 3.1 on 2022-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0024_auto_20220329_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='album_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
