# Generated by Django 3.1 on 2022-04-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0025_auto_20220425_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogalbum',
            options={'ordering': ['album_order']},
        ),
    ]
