# Generated by Django 3.1 on 2022-07-07 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0027_remove_catalogalbum_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplevelcategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
