# Generated by Django 3.1 on 2022-07-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0028_toplevelcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='topLevelCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='catalogAlbum.toplevelcategory'),
        ),
    ]
