# Generated by Django 3.1 on 2022-08-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0030_toplevelcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True, verbose_name='slug'),
        ),
    ]
