# Generated by Django 3.1 on 2022-08-09 10:09

from django.db import migrations, models


def rename_slug_duplicates(apps, schema_editor):
    CatalogAlbum = apps.get_model('catalogAlbum', 'CatalogAlbum')
    print('Rename slug duplicates for CatalogAlbum')
    
    for album in CatalogAlbum.objects.all():
        if album.slug and CatalogAlbum.objects.filter(slug=album.slug).count() > 1:
            album.slug = None
            album.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0030_toplevelcategory_slug'),
    ]

    operations = [
        migrations.RunPython(rename_slug_duplicates), # Include the remove duplicates operation
        migrations.AlterField(
            model_name='catalogalbum',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True, verbose_name='slug'),
        ),
    ]
