# Generated by Django 3.1 on 2022-08-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0031_auto_20220809_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='show_on_main_page',
            field=models.BooleanField(default=False, verbose_name='show on main page'),
        ),
    ]
