# Generated by Django 3.1 on 2024-04-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0034_auto_20240411_1421'),
    ]

    operations = [
        
    ]
