# Generated by Django 3.1 on 2024-04-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0035_auto_20240411_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogalbum',
            unique_together={('slug', 'topLevelCategory')},
        ),
    ]
