# Generated by Django 3.1 on 2024-04-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0036_auto_20240411_1435'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogalbum',
            unique_together=set(),
        ),
    ]
