# Generated by Django 3.1 on 2024-04-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0037_auto_20240411_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogalbum',
            name='is_campain',
        ),
        migrations.RemoveField(
            model_name='catalogalbum',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='catalogalbum',
            name='show_on_main_page',
        ),
    ]
