# Generated by Django 3.1 on 2024-04-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0038_auto_20240411_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toplevelcategory',
            options={'ordering': ('my_order',), 'verbose_name': 'top level category', 'verbose_name_plural': 'top level categories'},
        ),
        migrations.AlterField(
            model_name='toplevelcategory',
            name='my_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='toplevelcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
