# Generated by Django 3.1 on 2024-04-21 03:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0040_auto_20240417_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='throughimage',
            options={'ordering': ['image_order'], 'verbose_name': 'extra category', 'verbose_name_plural': 'extra categories'},
        ),
        migrations.RemoveField(
            model_name='catalogalbum',
            name='cimage',
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='תמונה'),
        ),
    ]
