# Generated by Django 3.1 on 2024-01-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productSize', '0011_auto_20230702_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='productSizeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sizes', models.ManyToManyField(blank=True, to='productSize.ProductSize')),
            ],
        ),
    ]
