# Generated by Django 3.1 on 2024-02-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productSizeGroup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizegroup',
            name='sizes',
        ),
    ]
