# Generated by Django 3.0.8 on 2021-10-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogLogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloglogo',
            name='cimg',
            field=models.URLField(blank=True, max_length=2047, null=True, verbose_name='claudinary url'),
        ),
    ]
