# Generated by Django 3.1 on 2024-04-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogLogos', '0003_auto_20211031_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogLogo',
        ),
    ]
