# Generated by Django 3.1 on 2022-11-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareableCart',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('times_used', models.IntegerField(default=0)),
                ('logs', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
