# Generated by Django 3.1 on 2022-11-03 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shareableCarts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablecart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
