# Generated by Django 3.1 on 2024-04-11 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shareableCarts', '0002_auto_20221103_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareablecart',
            options={'verbose_name': 'shareable cart', 'verbose_name_plural': 'shareable carts'},
        ),
        migrations.AlterField(
            model_name='shareablecart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='shareablecart',
            name='data',
            field=models.JSONField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='shareablecart',
            name='logs',
            field=models.JSONField(blank=True, null=True, verbose_name='logs'),
        ),
        migrations.AlterField(
            model_name='shareablecart',
            name='times_used',
            field=models.IntegerField(default=0, verbose_name='times used'),
        ),
        migrations.AlterField(
            model_name='shareablecart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid'),
        ),
    ]
