# Generated by Django 3.1 on 2022-03-16 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0005_auto_20220222_1012'),
        ('catalogImages', '0048_auto_20220309_0825'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0003_auto_20211013_1947'),
        ('productSize', '0002_auto_20210330_0407'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEnterItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKUM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='color.color')),
            ],
        ),
        migrations.RemoveField(
            model_name='ppn',
            name='fastProductTitle',
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('avgPrice', models.DecimalField(decimal_places=5, max_digits=5)),
                ('buyHistory', models.ManyToManyField(blank=True, related_name='buyHistory', to='inventory.ProductEnterItems')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.skum')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.ManyToManyField(blank=True, related_name='warehouse', to='inventory.WarehouseStock')),
            ],
        ),
        migrations.AddField(
            model_name='skum',
            name='ppn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ppn'),
        ),
        migrations.AddField(
            model_name='skum',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productSize.productsize'),
        ),
        migrations.AddField(
            model_name='skum',
            name='verient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogImages.catalogimagevarient'),
        ),
        migrations.AddField(
            model_name='productenteritems',
            name='sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.skum'),
        ),
        migrations.CreateModel(
            name='DocStockEnter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isAplied', models.BooleanField(default=False)),
                ('byUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='DocStockEnter', to='inventory.ProductEnterItems')),
                ('provider', models.ForeignKey(default=7, on_delete=django.db.models.deletion.SET_DEFAULT, to='provider.provider')),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='skum',
            unique_together={('ppn', 'size', 'color', 'verient')},
        ),
    ]
