# Generated by Django 3.1 on 2022-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220316_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenteritems',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='avgPrice',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
