# Generated by Django 3.1 on 2022-03-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220316_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='docstockenter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
