# Generated by Django 3.1 on 2022-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_docstockenter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='docstockenter',
            name='docNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
