# Generated by Django 3.1 on 2022-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_docstockenter_docnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstockenter',
            name='items',
            field=models.ManyToManyField(related_name='doc', to='inventory.ProductEnterItems'),
        ),
    ]
