# Generated by Django 3.1 on 2022-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20220321_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstockenter',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='doc', to='inventory.ProductEnterItems'),
        ),
    ]
