# Generated by Django 3.1 on 2022-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20220405_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppn',
            name='last_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
