# Generated by Django 3.1 on 2022-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_ppn_last_buy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppn',
            old_name='last_buy_price',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='ppn',
            name='store_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
