# Generated by Django 3.1 on 2022-04-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20211013_1947'),
        ('catalogImages', '0054_auto_20220414_1037'),
        ('inventory', '0009_auto_20220417_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppn',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Buy Price (no tax)'),
        ),
        migrations.AlterField(
            model_name='ppn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='ppn',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogImages.catalogimage', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='ppn',
            name='provider',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.SET_DEFAULT, to='provider.provider', verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='ppn',
            name='providerProductName',
            field=models.CharField(max_length=100, verbose_name='product provider name'),
        ),
        migrations.AlterField(
            model_name='ppn',
            name='store_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Store Price (no tax)'),
        ),
    ]
