# Generated by Django 3.1 on 2022-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20220417_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppn',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='barcode'),
        ),
    ]
