# Generated by Django 3.1 on 2022-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20220510_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productenteritems',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='productenteritemsentries',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
