# Generated by Django 3.1 on 2022-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20220510_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenteritems',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='item', to='inventory.ProductEnterItemsEntries'),
        ),
        migrations.AlterField(
            model_name='productenteritems',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
