# Generated by Django 3.1 on 2022-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20220511_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenteritems',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
