# Generated by Django 3.1 on 2022-05-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productenteritems_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppn',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.warehouse', verbose_name='default warehouse'),
        ),
        migrations.AddField(
            model_name='productenteritems',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.warehouse'),
        ),
    ]
