# Generated by Django 3.1 on 2022-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20220513_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstockenter',
            name='new_products',
            field=models.JSONField(default=list),
        ),
    ]
