# Generated by Django 3.1 on 2022-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20220513_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstockenter',
            name='new_products',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
