# Generated by Django 3.1 on 2022-05-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0055_auto_20220424_1335'),
        ('provider', '0003_auto_20211013_1947'),
        ('productSize', '0002_auto_20210330_0407'),
        ('color', '0005_auto_20220222_1012'),
        ('inventory', '0019_auto_20220515_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productenteritems',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='stock',
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='color.color'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='ppn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.ppn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productSize.productsize'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='verient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogImages.catalogimagevarient'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ppn',
            unique_together={('provider', 'providerProductName', 'barcode')},
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('warehouse', 'ppn', 'size', 'color', 'verient')},
        ),
        migrations.RemoveField(
            model_name='ppn',
            name='default_warehouse',
        ),
    ]
