# Generated by Django 3.1 on 2022-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20220515_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousestock',
            name='avgPrice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
