# Generated by Django 3.1 on 2022-05-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0022_auto_20220519_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_object_id', models.PositiveIntegerField()),
                ('to_object_id', models.PositiveIntegerField()),
                ('from_new_quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('to_new_quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock_history_from', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock_history_to', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'warehouse stock history',
                'verbose_name_plural': 'warehouse stock history',
            },
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='history',
            field=models.ManyToManyField(blank=True, to='inventory.WarehouseStockHistory'),
        ),
    ]
