# Generated by Django 3.1 on 2022-05-22 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0023_auto_20220519_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestockhistory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='warehousestockhistory',
            name='user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehousestockhistory',
            name='from_new_quantity',
            field=models.IntegerField(default=0, verbose_name='from quantity'),
        ),
        migrations.AlterField(
            model_name='warehousestockhistory',
            name='to_new_quantity',
            field=models.IntegerField(default=0, verbose_name='to quantity'),
        ),
    ]
