# Generated by Django 3.1 on 2022-05-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20220522_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestockhistory',
            name='from_content_type',
        ),
        migrations.RemoveField(
            model_name='warehousestockhistory',
            name='from_new_quantity',
        ),
        migrations.RemoveField(
            model_name='warehousestockhistory',
            name='from_object_id',
        ),
        migrations.RemoveField(
            model_name='warehousestockhistory',
            name='to_content_type',
        ),
        migrations.RemoveField(
            model_name='warehousestockhistory',
            name='to_new_quantity',
        ),
        migrations.RemoveField(
            model_name='warehousestockhistory',
            name='to_object_id',
        ),
        migrations.AddField(
            model_name='warehousestockhistory',
            name='new_quantity',
            field=models.IntegerField(default=0, verbose_name='new quantity'),
        ),
        migrations.AddField(
            model_name='warehousestockhistory',
            name='old_quantity',
            field=models.IntegerField(default=0, verbose_name='old quantity'),
        ),
    ]
