# Generated by Django 3.1 on 2022-05-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20220523_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productenteritems',
            options={'ordering': ('ppn__product__title',)},
        ),
        migrations.RemoveField(
            model_name='productenteritems',
            name='barcode',
        ),
    ]
