# Generated by Django 3.1 on 2022-05-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20211013_1947'),
        ('inventory', '0027_auto_20220523_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ppn',
            unique_together={('provider', 'providerProductName', 'barcode', 'has_phisical_barcode')},
        ),
    ]
