# Generated by Django 3.1 on 2022-06-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20211013_1947'),
        ('inventory', '0030_auto_20220602_1851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ppn',
            unique_together={('provider', 'providerProductName', 'barcode', 'has_phisical_barcode', 'providerMakat')},
        ),
    ]
