# Generated by Django 3.1 on 2022-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20220626_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenteritems',
            name='provider',
            field=models.ManyToManyField(blank=True, related_name='providerItems', to='inventory.ProviderRequestToEnter'),
        ),
    ]
