# Generated by Django 3.1 on 2022-06-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20220626_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productenteritems',
            old_name='provider',
            new_name='providerRequests',
        ),
    ]
