# Generated by Django 3.1 on 2024-04-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0065_auto_20240411_0828'),
        ('catalogImageAttrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprices',
            name='prices',
        ),
        migrations.DeleteModel(
            name='ProductPriceEntry',
        ),
        migrations.DeleteModel(
            name='ProductPrices',
        ),
    ]
