# Generated by Django 3.0.8 on 2020-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogImages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLikedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='שם')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל')),
                ('tel', models.CharField(max_length=30, verbose_name='phone number')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='message')),
                ('submit_date', models.DateTimeField(auto_now=True, verbose_name='submited date')),
                ('images', models.ManyToManyField(to='catalogImages.CatalogImage')),
            ],
        ),
    ]
