# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientLikedImages', '0002_auto_20210127_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlikedimage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='clientlikedimage',
            name='msg',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='clientlikedimage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
