# Generated by Django 3.0.8 on 2020-11-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productColor', '0001_initial'),
        ('product', '0001_initial'),
        ('productSize', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='כמות')),
                ('add_printing', models.BooleanField(verbose_name='הוסף הדפסה')),
                ('add_embroidery', models.BooleanField(verbose_name='הוסף רקמה')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productColor.ProductColor', verbose_name='צבע')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='הזמנה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='מוצר')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.ProductSize', verbose_name='גודל')),
            ],
            options={
                'verbose_name': 'פרטי הזמנה',
                'verbose_name_plural': 'פרטי הזמנות',
            },
        ),
    ]
