# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0002_auto_20210330_0407'),
        ('order', '0002_auto_20210330_0407'),
        ('product', '0003_auto_20210330_0407'),
        ('productSize', '0002_auto_20210330_0407'),
        ('order_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Order detail', 'verbose_name_plural': 'Order details'},
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='add_embroidery',
            field=models.BooleanField(verbose_name='add embroidery'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='add_printing',
            field=models.BooleanField(verbose_name='add printing'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.IntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productColor.ProductColor', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.ProductSize', verbose_name='size'),
        ),
    ]
