# Generated by Django 3.1 on 2022-03-30 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmBusinessTypeSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('my_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('my_order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrmIntrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='CrmTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='CrmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('businessName', models.CharField(max_length=100, verbose_name='business name')),
                ('businessType', models.CharField(blank=True, max_length=100, null=True, verbose_name='business type')),
                ('businessTypeCustom', models.CharField(blank=True, max_length=100, null=True, verbose_name='business type custom')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('want_emails', models.BooleanField(default=True, verbose_name='want emails')),
                ('want_whatsapp', models.BooleanField(default=True, verbose_name='want whatsapp')),
                ('flashy_contact_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='flashy contact id')),
                ('businessSelect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcrm.crmbusinesstypeselect', verbose_name='business')),
                ('intrested', models.ManyToManyField(blank=True, to='mcrm.CrmIntrest', verbose_name='intrested')),
                ('tags', models.ManyToManyField(blank=True, to='mcrm.CrmTag', verbose_name='tags')),
            ],
            options={
                'unique_together': {('businessName', 'businessSelect', 'businessType', 'businessTypeCustom', 'name')},
            },
        ),
    ]
