# Generated by Django 3.1 on 2022-01-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0002_crmuser_flashy_contact_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crmuser',
            unique_together={('businessName', 'name')},
        ),
    ]
