# Generated by Django 3.1 on 2022-01-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0003_auto_20220115_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='businessName',
            field=models.CharField(max_length=100, verbose_name='business name'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='businessType',
            field=models.CharField(max_length=100, verbose_name='business type'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='businessTypeCustom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='business type custom'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='flashy_contact_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='flashy contact id'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='want_emails',
            field=models.BooleanField(default=True, verbose_name='want emails'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='want_whatsapp',
            field=models.BooleanField(default=True, verbose_name='want whatsapp'),
        ),
    ]
