# Generated by Django 3.1 on 2022-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0006_auto_20220322_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
    ]
