# Generated by Django 3.1 on 2022-03-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0007_crmuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmIntrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='crmuser',
            name='intrested',
            field=models.ManyToManyField(blank=True, to='mcrm.CrmIntrest', verbose_name='intrested'),
        ),
    ]
