# Generated by Django 3.1 on 2022-03-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0008_auto_20220324_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmBusinessTypeSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='crmuser',
            unique_together={('businessName', 'businessType', 'businessTypeCustom', 'name', 'phone', 'email', 'address')},
        ),
        migrations.AddField(
            model_name='crmuser',
            name='businessSelect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcrm.crmbusinesstypeselect', verbose_name='business'),
        ),
    ]
