# Generated by Django 3.1 on 2022-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0009_auto_20220328_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmbusinesstypeselect',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='crmbusinesstypeselect',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
