# Generated by Django 3.1 on 2022-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0011_auto_20220328_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmbusinesstypeselect',
            options={'ordering': ('my_order',)},
        ),
        migrations.AlterField(
            model_name='crmbusinesstypeselect',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
