# Generated by Django 3.1 on 2022-03-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0012_auto_20220328_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='businessType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='business type'),
        ),
        migrations.AlterUniqueTogether(
            name='crmuser',
            unique_together={('businessName', 'businessSelect', 'name')},
        ),
    ]
