# Generated by Django 3.1 on 2022-03-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0013_auto_20220329_1856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crmuser',
            unique_together=set(),
        ),
    ]
