# Generated by Django 3.1 on 2022-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0016_auto_20220329_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='businessType',
            field=models.CharField(default='ttt', max_length=100, verbose_name='business type'),
            preserve_default=False,
        ),
    ]
