# Generated by Django 3.1 on 2022-03-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0017_auto_20220329_1904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crmuser',
            unique_together={('businessName', 'name')},
        ),
    ]
