# Generated by Django 3.1 on 2022-03-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcrm', '0019_auto_20220329_2038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crmuser',
            unique_together={('businessName', 'businessType', 'businessTypeCustom')},
        ),
    ]
