# Generated by Django 3.0.8 on 2021-02-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormTask',
            fields=[
                ('usertask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myUserTasks.UserTask')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='שם')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='אימייל')),
                ('message', models.TextField(blank=True, max_length=1500, null=True, verbose_name='הודעה')),
                ('url', models.CharField(max_length=300)),
            ],
            bases=('myUserTasks.usertask',),
        ),
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
                ('tasks', models.ManyToManyField(to='myUserTasks.UserTask')),
            ],
        ),
    ]
