# Generated by Django 3.0.8 on 2021-02-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUserTasks', '0002_auto_20210225_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='session',
            field=models.CharField(blank=True, max_length=41, null=True),
        ),
    ]
