# Generated by Django 3.0.8 on 2021-02-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUserTasks', '0003_auto_20210225_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
