# Generated by Django 3.0.8 on 2021-03-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0003_catalogimage_sizes'),
        ('myUserTasks', '0005_usertask_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsTask',
            fields=[
                ('usertask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myUserTasks.UserTask')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='שם')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='אימייל')),
                ('products', models.ManyToManyField(to='catalogImages.CatalogImage')),
            ],
            bases=('myUserTasks.usertask',),
        ),
    ]
