# Generated by Django 3.0.8 on 2021-03-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUserTasks', '0006_productstask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='task_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('task_name', 'session')},
        ),
    ]
