# Generated by Django 3.0.8 on 2021-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUserTasks', '0007_auto_20210304_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='submited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together=set(),
        ),
    ]
