# Generated by Django 3.0.8 on 2021-03-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myUserTasks', '0008_auto_20210307_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('task_name', 'session', 'submited', 'created_date')},
        ),
    ]
