# Generated by Django 3.0.8 on 2021-03-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myUserTasks', '0009_auto_20210307_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together=set(),
        ),
    ]
