# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUserTasks', '0010_auto_20210307_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformtask',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactformtask',
            name='message',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactformtask',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productstask',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='productstask',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
    ]
