# Generated by Django 3.1 on 2024-04-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myUserTasks', '0011_auto_20210330_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstask',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productstask',
            name='usertask_ptr',
        ),
        migrations.DeleteModel(
            name='ContactFormTask',
        ),
        migrations.DeleteModel(
            name='ProductsTask',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
