# Generated by Django 3.1 on 2022-06-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0002_auto_20210330_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'default_related_name': 'productSizes', 'ordering': ('-code',), 'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
    ]
