# Generated by Django 3.1 on 2022-08-23 08:20

from django.db import migrations
def remove_one_size_dup(apps, schema_editor):
    CatalogImage = apps.get_model('catalogImages', 'CatalogImage')
    one_size_id_to_remove = 108
    all_catalog_images = CatalogImage.objects.filter(sizes__id__in=[one_size_id_to_remove])
    ProductSize = apps.get_model('productSize', 'ProductSize')
    one_size_obj_to_use = ProductSize.objects.get(id=86)
    for img in all_catalog_images:
        img.sizes.add(one_size_obj_to_use)
        img.sizes.remove(one_size_id_to_remove)
        img.save()
    MOrderItemEntry = apps.get_model('morders','MOrderItemEntry')
    all_morder_item_entreis = MOrderItemEntry.objects.filter(size__id=one_size_id_to_remove)
    for ent in all_morder_item_entreis:
        ent.size = one_size_obj_to_use
        ent.save()
    #ProductSize.objects.get(id=one_size_id_to_remove).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0003_auto_20220614_1254'),
    ]

    operations = [
        migrations.RunPython(remove_one_size_dup),
    ]
