# Generated by Django 3.1 on 2023-06-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0004_auto_20220823_1120'),
    ]

    operations = [
    ]
