# Generated by Django 3.1 on 2023-06-15 14:58

from django.db import migrations


def copy_all_productSize_from_size_to_size2(apps, schema_editor):
    ProductSize = apps.get_model('productSize', 'ProductSize')
    for productSize in ProductSize.objects.all():
        productSize.size2 = productSize.size
        productSize.save()


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0006_productsize_size2'),
    ]

    operations = [
        migrations.RunPython(copy_all_productSize_from_size_to_size2),
    ]
