# Generated by Django 3.1 on 2023-06-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0007_auto_20230615_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
    ]
