# Generated by Django 3.1 on 2023-06-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0008_remove_productsize_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='size2',
            new_name='size',
        ),
    ]
