# Generated by Django 3.1 on 2023-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0009_auto_20230615_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['code', 'order']},
        ),
        migrations.AddField(
            model_name='productsize',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='code'),
        ),
    ]
