# Generated by Django 3.1 on 2023-07-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0010_auto_20230615_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'default_related_name': 'productSizes', 'ordering': ['order', '-code'], 'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
    ]
