# Generated by Django 3.1 on 2024-04-09 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0011_auto_20230702_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Product size group',
                'verbose_name_plural': 'Product size groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productsize',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='productSize.productsizegroup'),
        ),
    ]
