# Generated by Django 3.1 on 2024-02-21 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productSizeGroup', '0002_remove_productsizegroup_sizes'),
        ('productSize', '0011_auto_20230702_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'default_related_name': 'productSizes', 'ordering': ['size_group', 'order'], 'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='code',
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productSizes', to='productSizeGroup.productsizegroup'),
        ),
    ]
