# Generated by Django 3.1 on 2024-04-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0012_auto_20240410_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'default_related_name': 'productSizes', 'ordering': ['group', 'order', '-code'], 'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
    ]
