# Generated by Django 3.1 on 2024-04-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0013_auto_20240411_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'default_related_name': 'productSizes', 'ordering': ['group', 'order', '-size'], 'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='code',
        ),
    ]
