# Generated by Django 3.0.8 on 2020-11-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now=True, verbose_name='תאריך הגשה')),
                ('client_name', models.CharField(max_length=50, verbose_name='שם לקוח')),
                ('private_compeny', models.CharField(max_length=50, verbose_name='חברה פרטית')),
                ('addres', models.CharField(max_length=100, verbose_name='כתובת')),
                ('telephone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('contact_man', models.CharField(max_length=50, verbose_name='איש קשר')),
                ('cellphone', models.CharField(max_length=20, verbose_name='נייד')),
            ],
            options={
                'verbose_name': 'הזמנה',
                'verbose_name_plural': 'הזמנות',
            },
        ),
    ]
