# Generated by Django 3.1 on 2022-06-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0027_auto_20220619_1322'),
        ('smartbee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartbeeResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultCodeId', models.IntegerField(default=0)),
                ('result', models.TextField(default='')),
                ('validationErrors', models.JSONField(default=dict)),
                ('morder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morders.morder')),
            ],
        ),
    ]
