# Generated by Django 3.1 on 2022-06-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbee', '0002_smartbeeresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbeeresults',
            name='validationErrors',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
