# Generated by Django 3.1 on 2022-08-30 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smartbee', '0003_auto_20220620_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbeeresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 30, 12, 52, 25, 54029, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
