# Generated by Django 3.1 on 2022-08-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbee', '0004_smartbeeresults_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbeeresults',
            name='resultId',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
