# Generated by Django 3.1 on 2022-08-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbee', '0005_smartbeeresults_resultid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartbeeresults',
            options={'ordering': ('created_at',)},
        ),
    ]
