# Generated by Django 3.1 on 2022-10-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0035_auto_20220908_1138'),
        ('smartbee', '0006_auto_20220830_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbeeresults',
            name='morder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='morders.morder'),
        ),
    ]
