# Generated by Django 3.1 on 2024-04-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbee', '0007_auto_20221020_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartbeeresults',
            name='morder',
        ),
        migrations.DeleteModel(
            name='SmartbeeTokens',
        ),
        migrations.DeleteModel(
            name='SmartbeeResults',
        ),
    ]
