# Generated by Django 3.0.8 on 2020-11-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('color_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='productColors', serialize=False, to='color.Color')),
                ('code', models.CharField(max_length=2, verbose_name='קוד')),
            ],
            options={
                'verbose_name': 'צבע מוצר',
                'verbose_name_plural': 'צבעי מוצר',
                'ordering': ('code',),
                'default_related_name': 'productColors',
            },
            bases=('color.color',),
        ),
    ]
