# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'default_related_name': 'productColors', 'ordering': ('code',), 'verbose_name': 'product color', 'verbose_name_plural': 'product colors'},
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='code',
            field=models.CharField(max_length=2, verbose_name='code'),
        ),
    ]
