# Generated by Django 3.0.8 on 2021-04-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210402_0331'),
        ('customerCart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCart',
        ),
    ]
