# Generated by Django 3.0.8 on 2021-09-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color', '0002_auto_20210330_0407'),
        ('provider', '0002_auto_20210330_0407'),
        ('productSize', '0002_auto_20210330_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.FloatField(verbose_name='cost price')),
                ('client_price', models.FloatField(verbose_name='store price')),
                ('recomended_price', models.FloatField(verbose_name='private client price')),
                ('colors', models.ManyToManyField(to='color.Color', verbose_name='colors')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
                ('sizes', models.ManyToManyField(to='productSize.ProductSize', verbose_name='sizes')),
            ],
        ),
    ]
