# Generated by Django 3.0.8 on 2021-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImageDetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimagedetail',
            name='providerMakat',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='provider makat'),
        ),
    ]
