# Generated by Django 3.0.8 on 2020-12-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='const_inst_client_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='const_inst_client_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='const_sing_client',
        ),
    ]
