# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210330_0407'),
        ('product', '0002_auto_20201202_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_embroidery',
            field=models.BooleanField(default=True, verbose_name='suport embroidery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_printing',
            field=models.BooleanField(default=True, verbose_name='suport printing'),
        ),
    ]
