# Generated by Django 3.0.8 on 2021-07-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0015_auto_20210411_2033'),
        ('product', '0003_auto_20210330_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_images',
            field=models.ManyToManyField(to='catalogImages.CatalogImage'),
        ),
    ]
