# Generated by Django 3.1 on 2024-04-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glofa_types', '0004_auto_20240411_0719'),
        ('stock', '0004_delete_stock'),
        ('productImages', '0003_delete_productimage'),
        ('product', '0004_auto_20210723_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
