# Generated by Django 3.0.8 on 2021-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeseContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('message', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
