# Generated by Django 3.0.8 on 2021-03-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210221_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('resultCount', models.IntegerField(verbose_name='number of results')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
