# Generated by Django 3.0.8 on 2021-03-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_usersearchdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchdata',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='usersearchdata',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
