# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210317_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besecontactinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='besecontactinformation',
            name='message',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='besecontactinformation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
