# Generated by Django 3.0.8 on 2021-04-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210330_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='besecontactinformation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='besecontactinformation',
            name='sumbited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='besecontactinformation',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='besecontactinformation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='besecontactinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='phone'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=120, unique=True)),
                ('contact', models.ManyToManyField(to='core.BeseContactInformation')),
            ],
        ),
    ]
