# Generated by Django 3.0.8 on 2021-04-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210402_0009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='besecontactinformation',
            unique_together={('name', 'phone', 'email', 'url', 'sumbited')},
        ),
    ]
