# Generated by Django 3.0.8 on 2021-04-02 00:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210402_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='besecontactinformation',
            name='formUUID',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='besecontactinformation',
            unique_together=set(),
        ),
    ]
