# Generated by Django 3.0.8 on 2021-04-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerCart', '0003_customercart'),
        ('core', '0009_auto_20210402_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='carts',
            field=models.ManyToManyField(to='customerCart.CustomerCart'),
        ),
    ]
