# Generated by Django 3.0.8 on 2021-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contactformmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodal',
            name='uid',
            field=models.UUIDField(blank=True, null=True, verbose_name='uuid'),
        ),
    ]
