# Generated by Django 3.0.8 on 2021-11-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0036_auto_20211031_1249'),
        ('core', '0014_auto_20211101_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sveltecartmodal',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalogImages.CatalogImage'),
        ),
    ]
