# Generated by Django 3.1 on 2021-11-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211104_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogEntry',
        ),
    ]
