# Generated by Django 3.1 on 2022-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20211215_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='sveltecartmodal',
            name='businessName',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='business name'),
        ),
    ]
