# Generated by Django 3.1 on 2022-02-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sveltecartproductentery_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCartTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=120, null=True, verbose_name='last ip')),
                ('active_cart_id', models.CharField(max_length=120, unique=True, verbose_name='active cart id')),
            ],
        ),
    ]
