# Generated by Django 3.1 on 2022-03-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220301_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sveltecartmodal',
            name='doneOrder',
            field=models.BooleanField(default=False, verbose_name='done order'),
        ),
        migrations.AlterField(
            model_name='sveltecartmodal',
            name='productsRaw',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='raw products'),
        ),
    ]
