# Generated by Django 3.1 on 2022-03-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220302_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sveltecartmodal',
            name='productsRaw',
            field=models.TextField(blank=True, null=True, verbose_name='raw products'),
        ),
    ]
