# Generated by Django 3.1 on 2022-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220303_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='sveltecartproductentery',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit price'),
        ),
    ]
