# Generated by Django 3.1 on 2022-04-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220322_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sveltecartmodal',
            name='order_type',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='order type'),
        ),
        migrations.AddField(
            model_name='sveltecartproductentery',
            name='embro',
            field=models.BooleanField(default=False, verbose_name='embro'),
        ),
        migrations.AddField(
            model_name='sveltecartproductentery',
            name='print',
            field=models.BooleanField(default=False, verbose_name='print'),
        ),
    ]
