# Generated by Django 3.1 on 2022-04-10 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_auto_20220410_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_product_photos/')),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='buy price')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='description')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
