# Generated by Django 3.1 on 2022-04-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_userproductphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductphoto',
            name='want_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='want price'),
        ),
    ]
