# Generated by Django 3.1 on 2022-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220412_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecarttracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='activecarttracker',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
    ]
