# Generated by Django 3.1 on 2022-04-25 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0036_auto_20220414_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sveltecartmodal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
