# Generated by Django 3.1 on 2022-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220425_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidersDocxTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('logs', models.JSONField(blank=True, null=True)),
                ('docx', models.FileField(blank=True, null=True, upload_to='docx')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('error', 'Error')], default='new', max_length=20)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
