# Generated by Django 3.1 on 2022-11-05 23:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20221102_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersdocxtask',
            name='docx',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./static/media_root/'), upload_to='docx'),
        ),
    ]
