# Generated by Django 3.1 on 2022-11-05 23:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20221106_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersdocxtask',
            name='docx',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='docx'),
        ),
    ]
