# Generated by Django 3.1 on 2023-06-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20221106_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersdocxtask',
            name='doc_names',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
