# Generated by Django 3.1 on 2023-09-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20230926_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sveltecartmodal',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Contact Name'),
        ),
    ]
