# Generated by Django 3.1 on 2024-04-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20240411_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveCartTracker',
        ),
    ]
