# Generated by Django 3.1 on 2023-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_sveltecartmodal_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sveltecartmodal',
            name='settlement',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='settlement'),
        ),
    ]
