# Generated by Django 3.1 on 2023-09-28 09:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_sveltecartmodal_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidersDocxTask2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morder_ids', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('logs', models.JSONField(blank=True, null=True)),
                ('docx', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='docx')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('error', 'Error')], default='new', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
