# Generated by Django 3.1 on 2023-09-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0055_morder_settlement'),
        ('core', '0046_providersdocxtask2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providersdocxtask2',
            name='morder_ids',
        ),
        migrations.AddField(
            model_name='providersdocxtask2',
            name='morders',
            field=models.ManyToManyField(blank=True, to='morders.MOrder'),
        ),
    ]
