# Generated by Django 3.0.8 on 2021-11-03 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0016_auto_20210914_0812'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='catalogAlbum.CatalogAlbum', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='client',
            name='howPay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.PaymantWay', verbose_name='payment way'),
        ),
        migrations.AlterField(
            model_name='client',
            name='isWithholdingTax',
            field=models.BooleanField(default=False, verbose_name='IsWithholdingTax'),
        ),
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ClientOrganizations', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tariff',
            field=models.SmallIntegerField(default=0, verbose_name='tariff (%)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whenPay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.PaymentTime', verbose_name='payment time'),
        ),
    ]
