# Generated by Django 3.1 on 2021-11-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20211103_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='businessName',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=120, verbose_name='email'),
            preserve_default=False,
        ),
    ]
