# Generated by Django 3.1 on 2021-11-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0005_userlogentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogentry',
            name='device',
        ),
        migrations.RemoveField(
            model_name='userlogentry',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='userlogentry',
            name='user',
        ),
        migrations.CreateModel(
            name='UserSessionLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='uuid')),
                ('device', models.CharField(blank=True, max_length=100, null=True, verbose_name='device')),
                ('is_active', models.BooleanField(default=True)),
                ('session_start_timestemp', models.DateTimeField(auto_now_add=True)),
                ('session_end_timestemp', models.DateTimeField(blank=True, null=True)),
                ('logs', models.ManyToManyField(blank=True, related_name='logs', to='client.UserLogEntry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
