# Generated by Django 3.1 on 2021-11-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20211124_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='howPay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.paymantway', verbose_name='payment way'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whenPay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.paymenttime', verbose_name='payment time'),
        ),
    ]
