# Generated by Django 3.1 on 2021-12-12 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionlogger',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=150, null=True, verbose_name='uuid'),
        ),
    ]
