# Generated by Django 3.1 on 2022-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20211212_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientType',
            field=models.CharField(choices=[('0', 'לא מוגר'), ('1', 'חנות פרטית'), ('2', 'חנות קיבוץ'), ('3', 'אחר')], default='0', max_length=10, verbose_name='client type'),
        ),
    ]
