# Generated by Django 3.1 on 2022-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_client_clienttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientType',
            field=models.CharField(choices=[(0, 'not defined'), (1, 'private'), (2, 'kibuttz')], default=0, max_length=10, verbose_name='client type'),
        ),
    ]
