# Generated by Django 3.1 on 2022-01-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20220116_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientType',
            field=models.CharField(choices=[(0, 'not defined'), (1, 'private'), (2, 'kibuttz')], default=0, max_length=50, verbose_name='client type'),
        ),
    ]
