# Generated by Django 3.1 on 2022-01-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20220118_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientType',
            field=models.CharField(choices=[('ND', 'לא מוגדר'), ('PR', 'פרטי'), ('KB', 'קיבוץ')], default='ND', max_length=50, verbose_name='client type'),
        ),
    ]
