# Generated by Django 3.1 on 2022-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20220124_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='show_prices',
            field=models.BooleanField(default=False, verbose_name='show prices'),
        ),
    ]
