# Generated by Django 3.1 on 2022-02-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0046_auto_20220131_1149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0015_client_show_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='ip')),
                ('is_answered', models.BooleanField(default=False, verbose_name='is answered')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='answer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogImages.catalogimage', verbose_name='product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
