# Generated by Django 3.1 on 2022-03-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_userquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='question'),
        ),
    ]
