# Generated by Django 3.1 on 2022-04-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20220301_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tariff',
            field=models.FloatField(default=0, verbose_name='tariff (%)'),
        ),
    ]
