# Generated by Django 3.1 on 2022-05-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20220414_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='buissnes_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='buissnes name'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
    ]
