# Generated by Django 3.1 on 2022-05-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20220501_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttype',
            name='tariff',
            field=models.FloatField(default=0, verbose_name='tariff (%)'),
        ),
    ]
