# Generated by Django 3.1 on 2024-04-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msCrm', '0015_auto_20240411_0828'),
        ('client', '0020_clienttype_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestion',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientOrganizations',
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.DeleteModel(
            name='PaymantWay',
        ),
        migrations.DeleteModel(
            name='PaymentTime',
        ),
        migrations.DeleteModel(
            name='UserQuestion',
        ),
    ]
