# Generated by Django 3.1 on 2022-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_clienttype_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=511, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='businessName',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='business name '),
        ),
        migrations.AlterField(
            model_name='client',
            name='contactMan',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='contact man'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contactManPhone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='contact man phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contactManPosition',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='contact man position'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=120, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='privateCompany',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='P.C.'),
        ),
    ]
