# Generated by Django 3.1 on 2024-04-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20240411_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersessionlogger',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='usersessionlogger',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLogEntry',
        ),
        migrations.DeleteModel(
            name='UserSessionLogger',
        ),
    ]
