# Generated by Django 3.0.8 on 2021-03-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingtype',
            options={'verbose_name': 'Packing type', 'verbose_name_plural': 'Packing types'},
        ),
    ]
