# Generated by Django 3.1 on 2022-10-07 11:15

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('morders', '0035_auto_20220908_1138'),
        ('color', '0005_auto_20220222_1012'),
        ('productSize', '0004_auto_20220823_1120'),
        ('catalogImages', '0062_auto_20220902_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOrderSignatureItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.ForeignKey(blank=True, default=76, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='color.color')),
                ('size', models.ForeignKey(blank=True, default=108, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='productSize.productsize')),
                ('varient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogImages.catalogimagevarient')),
            ],
        ),
        migrations.CreateModel(
            name='MOrderSignatureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('total_qyt', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('show_details', models.BooleanField(default=True)),
                ('details', models.ManyToManyField(to='docsSignature.MOrderSignatureItemDetail')),
            ],
        ),
        migrations.CreateModel(
            name='MOrderSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Signed', 'Signed')], default='Draft', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('items', models.ManyToManyField(to='docsSignature.MOrderSignatureItem')),
                ('related_omrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='morders.morder')),
            ],
        ),
    ]
