# Generated by Django 3.1 on 2022-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mordersignature',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='mordersignatureitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mordersignatureitem',
            name='total_qyt',
        ),
        migrations.AddField(
            model_name='mordersignature',
            name='signature_cimage',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='mordersignatureitem',
            name='cimage',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='mordersignature',
            name='items',
            field=models.ManyToManyField(blank=True, to='docsSignature.MOrderSignatureItem'),
        ),
    ]
