# Generated by Django 3.1 on 2022-10-07 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0002_auto_20221007_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='mordersignature',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
