# Generated by Django 3.1 on 2022-10-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0004_auto_20221007_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='mordersignature',
            name='signature_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
