# Generated by Django 3.1 on 2022-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0005_mordersignature_signature_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOrderSignatureSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cimage', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mordersignature',
            name='simulations',
            field=models.ManyToManyField(blank=True, to='docsSignature.MOrderSignatureSimulation'),
        ),
    ]
