# Generated by Django 3.1 on 2022-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0006_auto_20221023_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='mordersignature',
            name='user_info_fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mordersignature',
            name='user_info_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mordersignature',
            name='user_info_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
