# Generated by Django 3.1 on 2022-11-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0007_auto_20221026_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mordersignatureitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='mordersignaturesimulation',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='mordersignatureitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mordersignaturesimulation',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
