# Generated by Django 3.1 on 2023-05-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0038_auto_20230122_1434'),
        ('docsSignature', '0008_auto_20221102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mordersignature',
            name='related_omrder',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='morders.morder'),
        ),
    ]
