# Generated by Django 3.1 on 2023-05-07 11:18

from django.db import migrations, models
import django.db.models.deletion


def data_migration_0009(apps, schema_editor):
    MOrder = apps.get_model('morders', 'MOrder')
    MOrderSignature = apps.get_model('docsSignature', 'MOrderSignature')
    orders = MOrder.objects.all()
    for order in orders:
        latest_sig = MOrderSignature.objects.filter(
            related_omrder=order).order_by("-id").first()
        if latest_sig:
            MOrderSignature.objects.filter(
                related_omrder=order).exclude(id=latest_sig.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0038_auto_20230122_1434'),
        ('docsSignature', '0008_auto_20221102_1228'),
    ]

    operations = [
        # Run python script
        migrations.RunPython(
            code=data_migration_0009,
            reverse_code=migrations.RunPython.noop
        ),

        migrations.AlterField(
            model_name='mordersignature',
            name='related_omrder',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='morders.morder'),
        ),
    ]
