# Generated by Django 3.1 on 2023-05-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0038_auto_20230122_1434'),
        ('docsSignature', '0009_auto_20230507_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mordersignature',
            name='related_omrder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mordersignature', to='morders.morder'),
        ),
    ]
