# Generated by Django 3.1 on 2023-05-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morders', '0042_auto_20230130_1336'),
        ('docsSignature', '0010_auto_20230521_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='mordersignaturesimulation',
            name='products',
            field=models.ManyToManyField(to='docsSignature.MOrderSignatureItem'),
        ),
        migrations.CreateModel(
            name='MOrderSignatureSimulationConnectedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='morders.morderitementry')),
            ],
        ),
    ]
