# Generated by Django 3.1 on 2023-05-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0011_auto_20230526_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mordersignaturesimulation',
            name='products',
            field=models.ManyToManyField(to='docsSignature.MOrderSignatureSimulationConnectedItem'),
        ),
    ]
