# Generated by Django 3.1 on 2023-05-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0013_auto_20230526_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mordersignaturesimulationconnecteditem',
            old_name='quantity',
            new_name='amount',
        ),
    ]
