# Generated by Django 3.1 on 2024-04-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsSignature', '0014_auto_20230526_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mordersignatureitem',
            name='details',
        ),
        migrations.RemoveField(
            model_name='mordersignatureitemdetail',
            name='color',
        ),
        migrations.RemoveField(
            model_name='mordersignatureitemdetail',
            name='size',
        ),
        migrations.RemoveField(
            model_name='mordersignatureitemdetail',
            name='varient',
        ),
        migrations.RemoveField(
            model_name='mordersignaturesimulation',
            name='products',
        ),
        migrations.RemoveField(
            model_name='mordersignaturesimulationconnecteditem',
            name='item',
        ),
        migrations.DeleteModel(
            name='MOrderSignature',
        ),
        migrations.DeleteModel(
            name='MOrderSignatureItem',
        ),
        migrations.DeleteModel(
            name='MOrderSignatureItemDetail',
        ),
        migrations.DeleteModel(
            name='MOrderSignatureSimulation',
        ),
        migrations.DeleteModel(
            name='MOrderSignatureSimulationConnectedItem',
        ),
    ]
